//create channel
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_FAILURE = 'CREATE_CHANNEL_FAILURE';

//get all channel
export const GET_CHANNELS_REQUEST = 'GET_CHANNELS_REQUEST';
export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAILURE = 'GET_CHANNELS_FAILURE';

//get single channel
export const GET_CHANNEL_REQUEST = 'GET_CHANNEL_REQUEST';
export const GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS';
export const GET_CHANNEL_FAILURE = 'GET_CHANNEL_FAILURE';

//get channel messages
export const GET_CHANNEL_MESSAGES_REQUEST = 'GET_CHANNEL_MESSAGES_REQUEST';
export const GET_CHANNEL_MESSAGES_SUCCESS = 'GET_CHANNEL_MESSAGES_SUCCESS';
export const GET_CHANNEL_MESSAGES_FAILURE = 'GET_CHANNEL_MESSAGES_FAILURE';
export const ADD_MESSAGE_TO_STORE = 'ADD_MESSAGE_TO_STORE';

//join channel
export const JOIN_CHANNEL_REQUEST = 'JOIN_CHANNEL_REQUEST';
export const JOIN_CHANNEL_USER_NOTIFICATION = 'JOIN_CHANNEL_USER_NOTIFICATION';
export const JOIN_CHANNEL_NOTIFICATION = 'JOIN_CHANNEL_NOTIFICATION';
export const NAVIGATE_TO_CHANNEL = 'NAVIGATE_TO_CHANNEL';
